name: Automated Testing

on:
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test 1
        run: python find_lowest_number.py test_data/test1_input.txt test_data/output.txt
      - name: Compare Output with Expected
        run: diff test_data/output.txt test_data/test1_expected.txt

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test 2
        run: python find_lowest_number.py test_data/test2_input.txt test_data/output.txt
      - name: Compare Output with Expected
        run: diff test_data/output.txt test_data/test2_expected.txt

  test3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test 3
        run: python find_lowest_number.py test_data/test3_input.txt test_data/output.txt
      - name: Compare Output with Expected
        run: diff test_data/output.txt test_data/test3_expected.txt
